### ISSUE TITLE
[Request] Ability to set negative values for note debris velocity

### ISSUE THREAD

**Issue by othereevee** [Raemien/DebrisTweaksQuest#1]
This can already be done through manually editing the config file, but this is tedious and creates issues (Noteably debris with negative values being spawned on the wrong side, e.g. right debris being spawned on the left.) I think that debris flying backwards looks cool and should be added officially to this mod.

**Comment by othereevee** [comment]
I think this can be done by changing a single value to true, but don't quote me on this as I have no idea on coding quest mods. I forked the mod and made the changes but have no idea if they work.

**Comment by Raemien** [comment]
Hi there! The lower limit was initially going to extend to -3, though that posed a few issues in testing. While this is still a planned feature, as of now, the velocity increment's limits are set in place to avoid buggy behaviour.

**Comment by Raemien** [comment]
Looks like negative velocity values are no longer causing those aforementioned issues. The next release will feature increments which max out at -3, rather than 0.
