### ISSUE TITLE
[Bug] Crashing when Testing

### ISSUE THREAD

**Issue by ZaneDragonBorn** [Raemien/DebrisTweaksQuest#3]
The Game will crash on startup whenever selecting the test button (This seems to be happening to everyone lol). Starting the game back up works fine but Testing will break the game

### Details:
**BS Version:** 1.13.2
**BMBF Version:** 1.13.3
**Headset:** Oculus Quest (First one)
**OS Version:** V23
**Mod Version:** 1.0.0
*If you need anything else just ask*

**Comment by Raemien** [comment]
Hi there! Would you be able to provide a crash log? I haven't been able to reproduce the issue, though a log might provide some context as to what is causing the crash.

**Comment by ZaneDragonBorn** [comment]
How do I go about finding the Crash Logs?
