### ISSUE TITLE
[Bug] Rainbow particles are not coloured

### ISSUE THREAD

**Issue by JonnyVR1** [Raemien/DebrisTweaksQuest#4]
Please see this commit which fixes the issue on the PC version https://github.com/Shadnix-was-taken/BeatSaber-ParticleOverdrive/commit/301ccad1cb56ae0359cd9ee2df9efe4b77d36097

**Comment by Raemien** [comment]
Hi there!
It appears that you have the wrong repo, as DebrisTweaks does not affect cut particles.
Perhaps you'd like to check out [QuestParticleTuner?](https://github.com/SuperMarcus/QuestParticleTuner/)

**Comment by JonnyVR1** [comment]
Oops, my bad - apologies!

Thanks for the redirect to the correct repo :)
